name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
    name: Testing pyfsa with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install graphviz and needed libraries
        run: sudo apt-get install graphviz libgraphviz-dev

      - name: Install dependencies and script
        run: pip install .[tests]

      - name: Lint with flake8
        run: flake8

      - name: Run static type analyzer
        run: mypy

      - name: Test with pytest
        run: pytest tests/
